;/*FB_PKG_DELIM*/

__d("LexicalDevtoolsCore",["cr:9917"],(function(a,b,c,d,e,f){e.exports=b("cr:9917")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalDevtoolsCore.prod",["Lexical","LexicalHtml","LexicalLink","LexicalMark","LexicalTable","react"],(function $module_LexicalDevtoolsCore_prod(global,require,requireDynamic,requireLazy,module,exports){
'use strict';var _require_closure_react;var M=_require_closure_react||(_require_closure_react=require("react"));
var N=Object.freeze({"\t":"\\t","\n":"\\n"}),O=new RegExp(Object.keys(N).join("|"),"g"),P=Object.freeze({ancestorHasNextSibling:"|",ancestorIsLastChild:" ",hasNextSibling:"\u251c",isLastChild:"\u2514",selectedChar:"^",selectedLine:">"}),U=[function(a){return a.hasFormat("bold")&&"Bold";},function(a){return a.hasFormat("code")&&"Code";},function(a){return a.hasFormat("italic")&&"Italic";},function(a){return a.hasFormat("strikethrough")&&"Strikethrough";},function(a){return a.hasFormat("subscript")&&"Subscript";},function(a){return a.hasFormat("superscript")&&"Superscript";},function(a){return a.hasFormat("underline")&&
"Underline";}],aa=[function(a){return a.hasTextFormat("bold")&&"Bold";},function(a){return a.hasTextFormat("code")&&"Code";},function(a){return a.hasTextFormat("italic")&&"Italic";},function(a){return a.hasTextFormat("strikethrough")&&"Strikethrough";},function(a){return a.hasTextFormat("subscript")&&"Subscript";},function(a){return a.hasTextFormat("superscript")&&"Superscript";},function(a){return a.hasTextFormat("underline")&&"Underline";}],ba=[function(a){return a.isDirectionless()&&"Directionless";},function(a){return a.isUnmergeable()&&"Unmergeable";}],ca=[function(a){return a.isToken()&&"Token";},function(a){return a.isSegmented()&&"Segmented";}];
function da(a){var b="";var c=V(a);b+=": range "+(""!==c?"{ "+c+" }":"")+" "+(""!==a.style?"{ style: "+a.style+" } ":"");c=a.anchor;a=a.focus;var f=c.offset,d=a.offset;b+="\n  \u251C anchor { key: "+c.key+", offset: "+(null===f?"null":f)+", type: "+c.type+" }";return b+="\n  \u2514 focus { key: "+a.key+", offset: "+(null===d?"null":d)+", type: "+a.type+" }";}function ea(a){return require("Lexical").$isNodeSelection(a)?": node\n  \u2514 ["+Array.from(a._nodes).join(", ")+"]":"";}
function W(a,b,c){if(c===void 0){c=[];}a=a.getChildren();var f=a.length;a.forEach(function(d,k){b(d,c.concat(k===f-1?P.isLastChild:P.hasNextSibling));require("Lexical").$isElementNode(d)&&W(d,b,c.concat(k===f-1?P.ancestorIsLastChild:P.ancestorHasNextSibling));});}function X(a){return Object.entries(N).reduce(function(b,_ref){var c=_ref[0],f=_ref[1];return b.replace(new RegExp(c,"g"),String(f));},a);}
function fa(a){if(require("Lexical").$isTextNode(a)){var b=a.getTextContent();b=0===b.length?"(empty)":"\""+X(b)+"\"";a=[V(a),ha(a),ia(a)].filter(Boolean).join(", ");return[b,0!==a.length?"{ "+a+" }":null].filter(Boolean).join(" ").trim();}if(require("LexicalLink").$isLinkNode(a)){b=a.getURL();b=0===b.length?"(empty)":"\""+X(b)+"\"";var c=a.getTarget();null!=c&&(c="target: "+c);var f=Boolean;var d=a.getRel();null!=d&&(d="rel: "+d);a=a.getTitle();null!=a&&(a="title: "+a);a=[c,d,a].filter(f).join(", ");return[b,0!==a.length?"{ "+a+" }":null].filter(Boolean).join(" ").trim();}return require("Lexical").$isParagraphNode(a)?(
a=ja(a),""!==a?"{ "+a+" }":""):"";}function ja(a){var b=aa.map(function(c){return c(a);}).filter(Boolean).join(", ").toLocaleLowerCase();""!==b&&(b="format: "+b);return b;}function ha(a){var b=ba.map(function(c){return c(a);}).filter(Boolean).join(", ").toLocaleLowerCase();""!==b&&(b="detail: "+b);return b;}function ia(a){var b=ca.map(function(c){return c(a);}).filter(Boolean).join(", ").toLocaleLowerCase();""!==b&&(b="mode: "+b);return b;}
function V(a){var b=U.map(function(c){return c(a);}).filter(Boolean).join(", ").toLocaleLowerCase();""!==b&&(b="format: "+b);return b;}
function ka(_ref2){var a=_ref2.indent,b=_ref2.isSelected,c=_ref2.node,f=_ref2.nodeKeyDisplay,d=_ref2.selection,k=_ref2.typeDisplay;if(!require("Lexical").$isTextNode(c)||!require("Lexical").$isRangeSelection(d)||!b||require("Lexical").$isElementNode(c))return"";b=d.anchor;var m=d.focus;if(""===c.getTextContent()||b.getNode()===d.focus.getNode()&&b.offset===m.offset)return"";b=d.getStartEndPoints();if(require("Lexical").$isNodeSelection(d)||null===b)c=[-1,-1];else{var _b=b,h=_b[0],g=_b[1];m=c.getTextContent();var l=m.length;b=d=-1;if("text"===h.type&&"text"===g.type){var _ref3,_ref4,_ref5,_ref6;var v=h.getNode(),w=g.getNode();v===w&&c===v&&h.offset!==
g.offset?(_ref3=h.offset<g.offset?[h.offset,g.offset]:[g.offset,h.offset],d=_ref3[0],b=_ref3[1],_ref3):c===v?(_ref4=v.isBefore(w)?[h.offset,l]:[0,h.offset],d=_ref4[0],b=_ref4[1],_ref4):c===w?(_ref5=w.isBefore(v)?[g.offset,l]:[0,g.offset],d=_ref5[0],b=_ref5[1],_ref5):(_ref6=[0,l],d=_ref6[0],b=_ref6[1],_ref6);}c=(m.slice(0,d).match(O)||[]).length;m=(m.slice(d,b).match(O)||[]).length;c=[d+c,b+c+m];}var _c=c,r=_c[0],n=_c[1];if(r===n)return"";c=a[a.length-1]===P.hasNextSibling?P.ancestorHasNextSibling:P.ancestorIsLastChild;a=[].concat(a.slice(0,a.length-1),[c]);c=Array(r+1).fill(" ");d=Array(n-r).fill(P.selectedChar);f=Array(f.length+(k.length+
3)).fill(" ");return[P.selectedLine,a.join(" "),[].concat(f,c,d).join("")].join(" ")+"\n";}function Y(a,b){var c=Array(b++ +1).join("  "),f=Array(b-1).join("  "),d;for(var k=0;k<a.children.length;k++){d=document.createTextNode("\n"+c),a.insertBefore(d,a.children[k]),Y(a.children[k],b),a.lastElementChild===a.children[k]&&(d=document.createTextNode("\n"+f),a.appendChild(d));}return a;}
var oa=M.forwardRef(function(_ref7,r){var a=_ref7.treeTypeButtonClassName,b=_ref7.timeTravelButtonClassName,c=_ref7.timeTravelPanelSliderClassName,f=_ref7.timeTravelPanelButtonClassName,d=_ref7.viewClassName,k=_ref7.timeTravelPanelClassName,m=_ref7.editorState,h=_ref7.setEditorState,g=_ref7.setEditorReadOnly,l=_ref7.generateContent;var _M$useState=M.useState([]),n=_M$useState[0],v=_M$useState[1],_M$useState2=M.useState(""),w=_M$useState2[0],C=_M$useState2[1],_M$useState3=M.useState(!1),D=_M$useState3[0],Q=_M$useState3[1],_M$useState4=M.useState(!1),B=_M$useState4[0],la=_M$useState4[1],z=M.useRef(0),G=M.useRef(null),_M$useState5=M.useState(!1),E=_M$useState5[0],H=_M$useState5[1],_M$useState6=M.useState(!1),F=_M$useState6[0],ma=_M$useState6[1],_M$useState7=M.useState(!1),x=_M$useState7[0],na=_M$useState7[1],R=M.useRef(),I=M.useRef(0),J=M.useCallback(function(p){var t=
++I.current;l(p).then(function(y){t===I.current&&C(y);})["catch"](function(y){t===I.current&&C("Error rendering tree: "+y.message+"\n\nStack:\n"+y.stack);});},[l]);M.useEffect(function(){if(!x&&1E3<m._nodeMap.size&&(ma(!0),!x))return;R.current!==m&&(R.current=m,J(B),D||v(function(p){return[].concat(p,[[Date.now(),m]]);}));},[m,J,B,x,D]);var A=n.length;M.useEffect(function(){if(E){var p;var t=function t(){var y=z.current;y===A-1?H(!1):p=setTimeout(function(){z.current++;var S=z.current,T=G.current;null!==T&&(T.value=String(S));h(n[S][1]);t();},n[y+1][0]-n[y][0]);};
t();return function(){clearTimeout(p);};}},[n,E,A,h]);return M.createElement("div",{className:d},!x&&F?M.createElement("div",{style:{padding:20}},M.createElement("span",{style:{marginRight:20}},"Detected large EditorState, this can impact debugging performance."),M.createElement("button",{onClick:function onClick(){na(!0);},style:{background:"transparent",border:"1px solid white",color:"white",cursor:"pointer",padding:5}},"Show full tree")):null,x?null:M.createElement("button",{onClick:function onClick(){J(!B);la(!B);},className:a,type:"button"},
B?"Tree":"Export DOM"),!D&&(x||!F)&&2<A&&M.createElement("button",{onClick:function onClick(){g(!0);z.current=A-1;Q(!0);},className:b,type:"button"},"Time Travel"),(x||!F)&&M.createElement("pre",{ref:r},w),D&&(x||!F)&&M.createElement("div",{className:k},M.createElement("button",{className:f,onClick:function onClick(){z.current===A-1&&(z.current=1);H(!E);},type:"button"},E?"Pause":"Play"),M.createElement("input",{className:c,ref:G,onChange:function onChange(p){p=Number(p.target.value);var t=n[p];t&&(z.current=p,h(t[1]));},type:"range",min:"1",
max:A-1}),M.createElement("button",{className:f,onClick:function onClick(){g(!1);var p=n.length-1;h(n[p][1]);var t=G.current;null!==t&&(t.value=String(p));Q(!1);H(!1);},type:"button"},"Exit")));});function Z(a,b){var c=new Set();var _loop=function _loop(){if(_isArray){if(_i>=_iterator.length)return"break";_ref9=_iterator[_i++];}else{_i=_iterator.next();if(_i.done)return"break";_ref9=_i.value;}var _ref8=_ref9;var f=_ref8[0];c.add(a.registerCommand(f,function(d){b(function(k){k=[].concat(k);k.push({payload:d,type:f.type?f.type:"UNKNOWN"});10<k.length&&k.shift();return k;});return!1;},require("Lexical").COMMAND_PRIORITY_CRITICAL));};for(var _iterator=a._commands,_isArray=Array.isArray(_iterator),_i=0,_iterator=_isArray?_iterator:_iterator[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref9;var _ret=_loop();if(_ret==="break")break;}return function(){return c.forEach(function(f){return f();});};}exports.TreeView=oa;
exports.generateContent=function(a,b,c){var f=a.getEditorState(),d=a._config,k=a._compositionKey,m=a._editable;if(c){var g="";f.read(function(){var l=require("LexicalHtml").$generateHtmlFromNodes(a);var r=document.createElement("div");r.innerHTML=l.trim();g=Y(r,0).innerHTML;});return g;}var h=" root\n";c=f.read(function(){var g=require("Lexical").$getSelection();W(require("Lexical").$getRoot(),function(l,r){var n="("+l.getKey()+")",v=l.getType()||"",w=l.isSelected(),C=require("LexicalMark").$isMarkNode(l)?" id: [ "+l.getIDs().join(", ")+" ] ":"";h+=(w?P.selectedLine:" ")+" "+r.join(" ")+" "+n+" "+v+" "+C+" "+fa(l)+"\n";
h+=ka({indent:r,isSelected:w,node:l,nodeKeyDisplay:n,selection:g,typeDisplay:v});});return null===g?": null":require("Lexical").$isRangeSelection(g)?da(g):require("LexicalTable").$isTableSelection(g)?": table\n  \u2514 { table: "+g.tableKey+", anchorCell: "+g.anchor.key+", focusCell: "+g.focus.key+" }":ea(g);});h+="\n selection"+c;h+="\n\n commands:";if(b.length){for(var _iterator2=b,_isArray2=Array.isArray(_iterator2),_i2=0,_iterator2=_isArray2?_iterator2:_iterator2[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref11;if(_isArray2){if(_i2>=_iterator2.length)break;_ref11=_iterator2[_i2++];}else{_i2=_iterator2.next();if(_i2.done)break;_ref11=_i2.value;}var _ref12=_ref11;var _g=_ref12.type;var l=_ref12.payload;h+="\n  \u2514 { type: "+_g+", payload: "+(l instanceof Event?l.constructor.name:l)+" }";}}else h+="\n  \u2514 None dispatched.";h+="\n\n editor:";h+="\n  \u2514 namespace "+d.namespace;
null!==k&&(h+="\n  \u2514 compositionKey "+k);return h+="\n  \u2514 editable "+String(m);};exports.registerLexicalCommandLogger=Z;exports.useLexicalCommandsLog=function(a){var _M$useState8=M.useState([]),b=_M$useState8[0],c=_M$useState8[1];M.useEffect(function(){return Z(a,c);},[a]);return M.useMemo(function(){return b;},[b]);};}),null);